main:
  - name: About Me
    url: "/"
    weight: 10
  - name: Research
    url: /work
    weight: 20
  - name: Teaching
    url: /teaching
    weight: 25
  - name: Blog
    url: /blog/
    weight: 26
